# https://github.com/elastic/logstash-docker
FROM docker.elastic.co/logstash/logstash:6.5.2

# Add your logstash plugins setup here
RUN logstash-plugin install logstash-input-beats
#CMD "service logstash restart"
